(function () {
  var state = { active: true, settings: null, root: null, lastTap: 0, lastTouch: 0, taps: 0, solving: false, autoRequested: false, lastSolvedKey: '', stateTimer: null };
  var questionSelectors = ['.question', '.qtext', '.test-question', '.question-container', '[data-question]', '[class*="question"]', '[id*="question"]', 'fieldset', '[role="group"]', 'form'];

  function send(message) { return new Promise(function (resolve, reject) { chrome.runtime.sendMessage(message, function (response) { if (chrome.runtime.lastError) reject(chrome.runtime.lastError); else resolve(response); }); }); }
  function text(node) { return (node && (node.innerText || node.value) || '').replace(/\s+/g, ' ').trim(); }
  function isVisible(node) { if (!node || node.nodeType !== 1) return false; var style = window.getComputedStyle(node); return style.display !== 'none' && style.visibility !== 'hidden' && node.getAttribute('hidden') === null && node.getBoundingClientRect().width > 0; }
  function isAd(node) { if (node && String(node.tagName).toLowerCase() === 'iframe') return true; var current = node; for (var i = 0; current && i < 3; i++, current = current.parentElement) { var marker = ((current.id || '') + ' ' + (typeof current.className === 'string' ? current.className : '') + ' ' + (current.getAttribute('aria-label') || '')).toLowerCase(); if (/\b(ad|ads|adv|adsbygoogle|advert|advertisement|banner|sponsor|promo|реклама|рекламный)\b/.test(marker)) return true; } return false; }
  function getSetting(key, fallback) { return send({ type: 'getSettings' }).then(function (settings) { return settings && settings[key] !== undefined ? settings[key] : fallback; }); }
  function participantField(node) { var marker = ((node.name || '') + ' ' + (node.id || '') + ' ' + (node.placeholder || '') + ' ' + (node.getAttribute('aria-label') || '') + ' ' + text(node.closest('label')).slice(0, 100)).toLowerCase(); return /surname|last.?name|firstname|first.?name|фамил|имя|фио|participant|участник/.test(marker); }
  function isIntroForm() { var fields = Array.prototype.slice.call(document.querySelectorAll('input[type="text"], input:not([type]), textarea')).filter(function (node) { return isVisible(node) && !isAd(node) && participantField(node); }); if (!fields.length) return false; var root = fields[0].closest('form, fieldset, [class*="start"], [class*="intro"], [class*="participant"]') || fields[0].parentElement; return !root.querySelector('input[type="radio"], input[type="checkbox"], [role="radio"]'); }
  function answerNodes(root) { return Array.prototype.slice.call(root.querySelectorAll('input[type="radio"], input[type="checkbox"], [role="radio"], label, .answer, .qanswer, [class*="answer"], .variant, [class*="variant"], li, button')).filter(function (node) { return isVisible(node) && !isAd(node) && !(node.matches('input[type="radio"], input[type="checkbox"]') && node.closest('label')); }); }
  function findQuestion() { var candidates = questionSelectors.reduce(function (all, selector) { return all.concat(Array.prototype.slice.call(document.querySelectorAll(selector))); }, []); var unique = []; candidates.forEach(function (node) { if (unique.indexOf(node) < 0 && isVisible(node) && !isAd(node) && (!state.root || !state.root.contains(node))) unique.push(node); }); var ranked = unique.map(function (node) { var answers = answerNodes(node); var marker = ((node.className || '') + ' ' + (node.id || '')).toLowerCase(); var explicit = /question|qtext|variant|answer/.test(marker) ? 1 : 0; return { node: node, count: answers.length, explicit: explicit, size: text(node).length }; }).filter(function (item) { return item.size > 10 && (item.count >= 2 || item.explicit); }); ranked.sort(function (a, b) { return (b.explicit * 100 + b.count * 10) - (a.explicit * 100 + a.count * 10) || a.size - b.size; }); return ranked.length ? ranked[0].node : null; }
  function extractQuestionData() { if (isIntroForm()) return { type: 'intro' }; var questionEl = findQuestion(); if (!questionEl) return null; var seen = {}; var answers = answerNodes(questionEl).map(function (el, index) { return { index: index, text: text(el), element: el }; }).filter(function (item) { var key = item.text.toLowerCase(); if (!key || key.length > 500 || /далее|next|продолжить|реклама|advertisement/i.test(key) || seen[key]) return false; seen[key] = true; return true; }).slice(0, 30); var inputField = questionEl.querySelector('input[type="text"], textarea'); if (!answers.length && inputField) return { type: 'input', question: text(questionEl), inputElement: inputField }; if (answers.length < 2) return null; return { type: 'choice', question: text(questionEl), answers: answers }; }
  function buildPrompt(data) { return 'Ты — ассистент, который проходит тесты. Ответь ТОЛЬКО номером правильного варианта (одно число, без пояснений).\n\nВопрос: ' + data.question + '\n\nВарианты:\n' + data.answers.map(function (answer, index) { return (index + 1) + '. ' + answer.text; }).join('\n') + '\n\nПравильный вариант (только число):'; }
  function bindTap(element, handler) { element.addEventListener('touchend', function (event) { event.preventDefault(); state.lastTouch = Date.now(); handler(event); }, { passive: false }); element.addEventListener('click', function (event) { if (Date.now() - state.lastTouch > 500) handler(event); }); }
  function clickOption(item) { var input = item.element.matches('label') ? item.element.querySelector('input') : item.element.closest('label') && item.element.closest('label').querySelector('input'); (input || item.element).dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true, view: window })); if (input && !input.checked) input.click(); }
  function questionSignature(data) { return data.question + '|' + data.answers.map(function (answer) { return answer.text; }).join('|'); }
  function isTestFinished() { var selectors = ['[class*="result"]', '[id*="result"]', '[class*="finish"]', '[id*="finish"]', '[class*="complete"]', '[id*="complete"]', '[class*="success"]', '[id*="success"]']; for (var i = 0; i < selectors.length; i++) { var nodes = document.querySelectorAll(selectors[i]); for (var j = 0; j < nodes.length; j++) { var node = nodes[j]; var marker = ((node.className || '') + ' ' + (node.id || '') + ' ' + text(node)).toLowerCase(); if (isVisible(node) && !isAd(node) && !node.matches('button, a, input, select, textarea') && text(node).length > 8 && /result|finish|complete|success|результат|заверш|окончен|итог/.test(marker)) return true; } } var bodyCopy = document.body.cloneNode(true); Array.prototype.slice.call(bodyCopy.querySelectorAll('button, a, input, select, textarea, script, style, nav')).forEach(function (node) { node.remove(); }); var page = text(bodyCopy); return /(?:тест|test).{0,30}(?:заверш|окончен|finished|completed)|(?:ваш результат|итоговый результат|your score)/i.test(page); }
  function analyzeAndAnswer(inputData) { var data = inputData || extractQuestionData(); if (!data) { updateStatus('Вопрос пока не найден.'); return Promise.resolve(false); } if (data.type === 'intro') { updateStatus('Сначала заполните фамилию и имя.'); return Promise.resolve(false); } if (data.type !== 'choice') { updateStatus('Этот тип ответа пока не поддерживается.'); return Promise.resolve(false); } return send({ type: 'ask', prompt: buildPrompt(data), action: 'llmQuery' }).then(function (response) { if (!response || response.error || response.success === false) throw new Error(response && (response.error || 'LLM query failed') || 'LLM query failed'); var match = String(response.answer).match(/\d+/); if (!match) throw new Error('Не удалось извлечь номер ответа.'); var chosen = data.answers[parseInt(match[0], 10) - 1]; if (!chosen) throw new Error('Номер ответа вне диапазона.'); clickOption(chosen); return true; }); }
  function finishAutoSolve(message) { state.autoRequested = false; state.solving = false; updateStatus(message); setTimeout(function () { if (!state.autoRequested) { state.active = false; render(); } }, 900); }
  function autoSolveCycle() { if (!state.autoRequested || !state.active) { state.solving = false; return; } if (isTestFinished()) { finishAutoSolve('Тест завершён. Автоматизация выключена.'); return; } var data = extractQuestionData(); if (!data) { updateStatus('Жду вопрос…'); setTimeout(autoSolveCycle, 900); return; } if (data.type === 'intro') { updateStatus('Сначала заполните фамилию и имя.'); setTimeout(autoSolveCycle, 900); return; } if (data.type !== 'choice') { updateStatus('Этот тип ответа пока не поддерживается.'); setTimeout(autoSolveCycle, 1200); return; } var key = questionSignature(data); if (key === state.lastSolvedKey) { updateStatus('Ответ выбран. Нажмите «Далее» вручную.'); setTimeout(autoSolveCycle, 900); return; } analyzeAndAnswer(data).then(function (result) { if (result) { state.lastSolvedKey = key; updateStatus('Ответ выбран. «Далее» не нажимаю.'); } setTimeout(autoSolveCycle, 900); }).catch(function (error) { state.autoRequested = false; state.solving = false; updateStatus(error.message); if (state.root) setPanelOpen(state.root.querySelector('.orion-ai-panel'), true); }); }
  function startAutoSolve() { if (state.solving) return; state.autoRequested = true; state.solving = true; state.lastSolvedKey = ''; updateStatus('Обрабатываю…'); autoSolveCycle(); }
  function updateStatus(value) { if (state.root) { var status = state.root.querySelector('.orion-ai-status'); if (status) status.textContent = value; } }
  function setPanelOpen(panel, open) { var isOpen = Boolean(open); panel.classList.toggle('is-open', isOpen); if (state.root) { state.root.classList.toggle('is-panel-open', isOpen); var fab = state.root.querySelector('.orion-ai-fab'); if (fab) fab.setAttribute('aria-expanded', isOpen ? 'true' : 'false'); } }
  function syncPageState() { if (!state.root) return; var intro = isIntroForm(); var action = state.root.querySelector('.orion-ai-action'); if (action) action.disabled = intro; if (intro) { setPanelOpen(state.root.querySelector('.orion-ai-panel'), false); updateStatus('Заполните данные участника'); } else if (state.root.querySelector('.orion-ai-status').textContent === 'Заполните данные участника') updateStatus('Готово'); }
  function render() { if (state.root) state.root.remove(); if (!state.settings || !state.settings.showFab || !state.active) return; state.root = document.createElement('div'); state.root.id = 'orion-ai-root'; state.root.innerHTML = '<div class="orion-ai-panel"><p class="orion-ai-status">Готово</p><p class="orion-ai-timer"></p></div><button class="orion-ai-fab" type="button" aria-label="Решить текущий вопрос" aria-expanded="false"></button><button class="orion-ai-close" type="button" aria-label="Остановить и свернуть">×</button>'; document.documentElement.appendChild(state.root); var panel = state.root.querySelector('.orion-ai-panel'); var fab = state.root.querySelector('.orion-ai-fab'); bindTap(fab, function () { if (state.solving) { state.autoRequested = false; state.solving = false; return; } setPanelOpen(panel, false); startAutoSolve(); }); bindTap(state.root.querySelector('.orion-ai-close'), function () { state.active = false; state.autoRequested = false; state.solving = false; chrome.storage.local.set({ autoSolveRunning: false }); render(); }); syncPageState(); }
  function restoreGesture(event) { if (state.root && state.root.contains(event.target)) return; if (event.type === 'touchstart') state.lastTouch = Date.now(); if (event.type === 'click' && Date.now() - state.lastTouch < 500) return; var now = Date.now(); if (now - state.lastTap > 900) state.taps = 0; state.lastTap = now; state.taps++; if (state.taps >= 3) { state.taps = 0; state.active = !state.active; if (!state.active) { state.autoRequested = false; state.solving = false; } render(); } }
  function scheduleStateSync() { clearTimeout(state.stateTimer); state.stateTimer = setTimeout(syncPageState, 200); }
  document.addEventListener('touchstart', restoreGesture, { passive: true }); document.addEventListener('click', restoreGesture, { passive: true }); document.addEventListener('input', scheduleStateSync, true); document.addEventListener('change', scheduleStateSync, true);
  if (window.MutationObserver) new MutationObserver(scheduleStateSync).observe(document.documentElement, { childList: true, subtree: true, attributes: true, attributeFilter: ['class', 'style', 'hidden'] });
  send({ type: 'getSettings' }).then(function (settings) { state.settings = settings || { showFab: true }; render(); }).catch(function () { state.settings = { showFab: true }; render(); });
  if (chrome.storage.onChanged) chrome.storage.onChanged.addListener(function (changes, area) { if (area !== 'local' || !state.settings) return; Object.keys(changes).forEach(function (key) { state.settings[key] = changes[key].newValue; }); render(); });
}());
